export const FilterData = {
  title: {
    value: "title",
    textValue: "",
    selectValue: "3",
    change: false,
  },
  Inventory: {
    value: "items.quantity",
    textValue: "",
    selectValue: "1",
    change: false,
  },
  SKU: {
    value: "items.sku",
    textValue: "",
    selectValue: "3",
    change: false,
  },
  Tags: {
    value: "tags",
    textValue: "",
    selectValue: "3",
    change: false,
  },
  "Product type": {
    value: "product_type",
    textValue: "",
    selectValue: "3",
    change: false,
  },
  Vendor: {
    value: "brand",
    textValue: "",
    selectValue: "equals",
    change: false,
  },
  "Template name": {
    value: "profile.profile_name",
    textValue: "",
    selectValue: "1",
    change: false,
  },
  "Product Status": {
    value: "items.status",
    textValue: "",
    selectValue: "1",
    change: false,
  },
  "Variant attributes": {
    value: "variant_attributes",
    textValue: "",
    selectValue: "1",
    change: false,
  },
  Activity: {
    value: "cif_amazon_multi_activity",
    textValue: "",
    selectValue: "1",
    change: false,
  },
  Type: {
    value: "type",
    textValue: "",
    selectValue: "1",
    change: false,
  },
  tabSelected: ["All", 0],
  query: ["", ""],
};
